### ISSUE TITLE
Geen verbinding (lokaal http)

### ISSUE THREAD

**Issue by CervezaStallone** [phavekes/p1monitor-android#2]
Lokaal krijg ik geen verbinding met mijn p1mon. Gelieve meer informatie te verstrekken tbv het configureren van de instellingen. 

Ik heb een api code ingevoerd, auth is p1mon + WW. 

![Screenshot_20240205_075121_P1 Monitor.jpg](https://github.com/phavekes/p1monitor-android/assets/48717031/70f8ce9a-b8f4-4c7b-abcf-03e0b3dec14c)

![Screenshot_20240205_075130_P1 Monitor.jpg](https://github.com/phavekes/p1monitor-android/assets/48717031/f8775bfa-0327-4193-b481-db0a3f7f9f0e)

![Screenshot_20240205_075140_P1 Monitor.jpg](https://github.com/phavekes/p1monitor-android/assets/48717031/0e31300b-ade2-49f0-abb9-1ac697667615)

**Comment by phavekes** [comment]
De foutmelding in de rode letters is duidelijk, jouw device staat communicatie zonder ssl (https) niet toe.
Dat kan de app niet veranderen.
